### ISSUE TITLE
tutorial 3 

### ISSUE THREAD

**Issue by MRebolle** [ci-group/revolve#75]
Tutorial 3 doesn't work with the current version of *revolve.py*. This is the error that comes up when executing it:

```
(.venv) (base) p058170:revolve tarigarma$ ./revolve.py --simulator-cmd=gazebo --manager experiments/examples/tutorial3.py 
STARTING
Traceback (most recent call last):
  File "./revolve.py", line 69, in <module>
    main()
  File "./revolve.py", line 62, in main
    run(loop, arguments)
  File "./revolve.py", line 28, in run
    manager = importlib.import_module(manager_lib).run
  File "/Users/tarigarma/revolve/.venv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/tarigarma/revolve/experiments/examples/tutorial3.py", line 11, in <module>
    from pygazebo.pygazebo import DisconnectError
ImportError: cannot import name 'DisconnectError' from 'pygazebo.pygazebo' (/Users/tarigarma/revolve/.venv/src/pygazebo/pygazebo/pygazebo.py)```

**Comment by portaloffreedom** [comment]
The tutorials are out of date, they need an update.
