### ISSUE TITLE
Python 3.8 Asyncio problems

### ISSUE THREAD

**Issue by DaanZ** [ci-group/revolve#90]
Both me and another student have problems with using Python 3.8, probably caused by an asyncio implementation problem.

```
Traceback (most recent call last):
  File "./revolve.py", line 69, in <module>
    main()
  File "./revolve.py", line 62, in main
    run(loop, arguments)
  File "./revolve.py", line 32, in run
    loop.run_until_complete(only_gazebo.run())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
asyncio.exceptions.CancelledError
[2020-05-08 06:16:15,168     gazebo] INFO     Terminating processes...
```
```
Exception handling an incoming connection
Traceback (most recent call last):
  File "/Users/lewis/revolve/.venv/src/pygazebo/pygazebo/connection.py", line 163, in read_raw
    header = await self._reader.readexactly(8)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 8 expected bytes
```

**Comment by EtorArza** [comment]
I assume the workaround in #107 fixes the issue. However, it would be nice that the code would work with newer versions of python as well.
